name: Docker torusd CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build torusd latest
        run: DOCKER_BUILDKIT=1 docker build --target torusd-unix --tag ghcr.io/torus-economy/torusd:latest .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/torus-economy/torusd:latest
