name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/torus-economy/torusd
          tags: |
            type=semver,pattern={{version}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/386,linux/arm/v7
          push: true
          target: torusd-unix
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile

  build-win:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install zip tool
        run: sudo apt-get install zip -y

      - name: Build TORUS-Qt.exe
        run: DOCKER_BUILDKIT=1 docker build --target torus-qt-win --tag torus-qt-win:latest .

      - name: Copy artifacts
        run: docker cp $(docker create --rm torus-qt-win):/opt/torus-core/release/TORUS-Qt.exe TORUS-Qt.exe

      - name: Zip artifacts
        run: zip torus-qt-win64.zip TORUS-Qt.exe

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: "torus-qt-win64.zip"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
